# Generated by Django 4.0.4 on 2022-11-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_drf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
